version: '3.8'

services:
  web:
    build: .
    command: sh -c "gunicorn --bind 0.0.0.0:5000 app:app"
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - app-network

  bot:
    build: .
    command: python3 forever.py
    volumes:
      - .:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - app-network

networks:
  app-network: